### ISSUE TITLE
Broken import for `LanguageCodes` 

### ISSUE THREAD

**Issue by carafelix** [grammyjs/commands#53]
Error introduced in #52 

running `deno task backport` returns:
```bash
src/deps.node.ts:22:5 - error TS2305: Module '"grammy/types"' has no exported member 'LanguageCode'.

22     LanguageCode,
       ~~~~~~~~~~~~
src/deps.node.ts:25:10 - error TS2305: Module '"grammy/types"' has no exported member 'LanguageCodes'.

25 export { LanguageCodes } from "grammy/types";
```

Using the plugin in a bot, starts it with the following error:
```bash
error: Uncaught SyntaxError: The requested module 'https://lib.deno.dev/x/grammy@1/types.ts' does not provide an export named 'LanguageCodes'
export { LanguageCodes } from "https://lib.deno.dev/x/grammy@1/types.ts";
         ^
    at <anonymous> (https://deno.land/x/grammy_commands@v1.0.0/deps.deno.ts:25:10)
```
